# This workflow name will appear on GitHub in the "Actions" tab.
name: Go CI

# This specifies when the workflow should run.
on:
  # Triggers the workflow on push events to the 'main' branch.
  push:
    branches:
      - main
  # Triggers the workflow on pull request events to the 'main' branch.
  pull_request:
    branches:
      - main

# Define the jobs that will run as part of this workflow.
jobs:
  build-and-test:
    # Specifies the runner environment for this job.
    runs-on: ubuntu-latest

    # Steps define a sequence of tasks that will be executed.
    steps:
      # Step 1: Checkout the repository code.
      # This action checks out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Go environment.
      # This action sets up a Go environment and caches Go modules.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Specify the Go version. You can change this to your desired version.
          go-version: '1.22'
          # Enable caching of Go modules to speed up subsequent runs.
          cache: true

      # Step 3: Download Go modules.
      # This step ensures all dependencies are downloaded before building or testing.
      - name: Download Go modules
        run: go mod download

      # Step 4: Run Go tests.
      # This command runs all tests in your package.
      # '-v' (verbose) shows detailed output for each test.
      # './...' recursively finds and runs tests in all subdirectories.
      - name: Run Go tests
        run: go test -v ./...

      # Step 5: (Optional) Run Go linting.
      # This step uses 'golangci-lint' for code quality checks.
      # You'll need to add a '.golangci.yml' config file in your repo for this to work effectively.
      # Install golangci-lint - Removed explicit version to let the installer pick the latest compatible version.
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6 # Use the latest stable version
        with:
          # Optional: specify a specific version of golangci-lint to use.
          # If not specified, the action will try to determine the latest compatible version.
          # version: v1.59.1 # Uncomment and change if you need a specific version

          # Optional: specify the path to the .golangci.yml config file.
          # config: path/to/.golangci.yml

          # Optional: only run against modified files (faster for PRs).
          # issues-exit-code: 1 # Default is 1

          # Optional: run linter against all Go files in the repository.
          # The default is to run on files changed in the pull request.
          args: --verbose ./...

  # New job: Release (tagging)
  # New job: Release (tagging)
  release:
    # This job only runs if the 'build-and-test' job succeeds.
    needs: build-and-test
    # This job only runs on pushes to the 'main' branch.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      # Grant write permission to the GITHUB_TOKEN to create tags.
      contents: write

    steps:
      - name: Checkout code
        # Fetch all history and tags to correctly determine the next version.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: fetch all history for proper tag detection

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Modified: Using a shell script to get the next semantic version
      - name: Get next semantic version
        id: tag
        run: |
          # Fetch all tags to ensure we have the complete history
          git fetch --tags --force
          
          # Get the latest tag. If no tags exist, default to v0.0.0.
          # We use `git describe --tags --abbrev=0` to get the latest annotated tag.
          # `2>/dev/null` suppresses errors if no tags are found.
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          echo "Latest tag found: $latest_tag"
          
          # Extract major, minor, and patch parts from the latest tag.
          # `sed 's/^v//'` removes a leading 'v' if present.
          # `tr '.' ' '` replaces dots with spaces for easy array parsing.
          IFS=' ' read -r -a version_parts <<< "$(echo "$latest_tag" | sed 's/^v//')"
          
          # Assign parts, defaulting to 0 if a part is missing (e.g., from v0.0.0)
          major=${version_parts[0]:-0}
          minor=${version_parts[1]:-0}
          patch=${version_parts[2]:-0}
          
          # Increment the patch version.
          new_patch=$((patch + 1))
          
          # Form the new tag, ensuring it starts with 'v'.
          new_tag="v${major}.${minor}.${new_patch}"
          
          echo "Determined next tag: $new_tag"
          # Set the output variable 'tag' for subsequent steps.
          echo "tag=$new_tag" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        # This step only runs if a new version tag was generated by the previous step.
        if: steps.tag.outputs.tag != ''
        run: |
          # Configure Git user for the commit/tag. These details are used in the tag creation.
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Create the new tag locally.
          git tag ${{ steps.tag.outputs.tag }}
          # Push the newly created tag to the remote repository.
          git push origin ${{ steps.tag.outputs.tag }}
          echo "Created and pushed tag: ${{ steps.tag.outputs.tag }}"
